### PR TITLE
Bold possible events based on the bag

### PR DESCRIPTION
**Pull request by garciabm**
This could help with " highlight concrete possibilities according to the bag" :)

Added logic to bold the possible events based on the bag, added logic to validate when there is only one cube, and logic to check when there is only one type of a cube don't bold the event with two of the same type.

### CODE REVIEW

**Comment by migius** [comment]
oh damn! we made the same thing in the same time! I just committed a solution, so i think that we don't need this pull request, do you agree?

**Comment by garciabm** [comment]
lol, what a coincidence. For sure, your change looks better, and also and most important. you are the owner :P

**Comment by migius** [comment]
I think you are not a native English speaker, the bug #15 might be for you. Just copy the object from en.js file in es.js and replace strings. (if you speak another language of course just add the file to folder and index.html)

**Comment by garciabm** [comment]
That sounds like a nice idea, for sure. In my free time I will try to translate the more I can. I will try to take a look to the files on spanish on bgg. Maybe that will help me a little.

**Pull request closed without merging**
